---
# tasks file for netiq-edirectory
- name: XDAS appenders
  ansible.builtin.template:
    src: xdasconfig.properties.j2
    dest: /etc/opt/novell/eDirectory/conf/xdasconfig.properties
    backup: true
    mode: 0644
  tags: edirectory

- name: SuSEfirewall2 eDirectory service
  become: true
  ansible.builtin.template:
    src: SuSEfirewall2.eDirectory.j2
    dest: /etc/sysconfig/SuSEfirewall2.d/services/eDirectory
    owner: root
    mode: 0644
    # notify:
  tags:
    - edirectory
    - firewall
